#!/bin/bash

echo "Cleaning build directory..."
rm -rf ../build_docs/html

echo "Setting up environment..."
# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export PYTHONPATH="$PROJECT_ROOT"
echo "PYTHONPATH set to: $PYTHONPATH"

# Create source/modules directory for generated files
mkdir -p "$PROJECT_ROOT/source/generated"

# Clean up any existing autogenerated files
rm -rf "$PROJECT_ROOT/source/generated/"*

# Add virtual environment handling - look in several possible locations
VENV_LOCATIONS=(
  "$PROJECT_ROOT/.venv"
  "$PROJECT_ROOT/venv"
  "$HOME/.venv/researchguide"
  "$HOME/venv/researchguide"
)

VENV_FOUND=false
for VENV_PATH in "${VENV_LOCATIONS[@]}"; do
    if [ -d "$VENV_PATH" ] && [ -f "$VENV_PATH/bin/activate" ]; then
        echo "Found virtual environment at: $VENV_PATH"
        source "$VENV_PATH/bin/activate"
        VENV_ACTIVATED=true
        VENV_FOUND=true
        break
    fi
done

if [ "$VENV_FOUND" = false ]; then
    echo "ERROR: No suitable virtual environment found."
    echo "Checked locations:"
    for VENV_PATH in "${VENV_LOCATIONS[@]}"; do
        echo "  - $VENV_PATH"
    done
    echo "Please create a virtual environment with Sphinx installed."
    echo "Example: python -m venv $PROJECT_ROOT/.venv && source $PROJECT_ROOT/.venv/bin/activate && pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints"
    exit 1
fi

# Check if sphinx is installed in the virtual environment
if ! command -v sphinx-build &>/dev/null; then
    echo "ERROR: sphinx-build not found in virtual environment."
    echo "Please install sphinx: pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints"
    [ "$VENV_ACTIVATED" = true ] && deactivate
    exit 1
fi

echo "Generating module documentation..."
cd "$PROJECT_ROOT" && sphinx-apidoc -f -o source/generated . -H "API Reference" -M -e --implicit-namespaces

echo "Building documentation..."
cd "$PROJECT_ROOT" && sphinx-build -b html -d build_docs/doctrees source build_docs/html

echo "Documentation build complete."
echo "Open $PROJECT_ROOT/build_docs/html/index.html in your browser to view."

# Deactivate virtual environment if we activated it
[ "$VENV_ACTIVATED" = true ] && deactivate
